/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'sizes' : IDL.Vec(IDL.Nat),
  'category' : IDL.Text,
  'price' : IDL.Nat64,
  'images' : IDL.Vec(IDL.Text),
});
export const SubmissionId = IDL.Nat;

export const idlService = IDL.Service({
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFilteredProducts' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat64),
        IDL.Opt(IDL.Nat64),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'submitForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [SubmissionId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'sizes' : IDL.Vec(IDL.Nat),
    'category' : IDL.Text,
    'price' : IDL.Nat64,
    'images' : IDL.Vec(IDL.Text),
  });
  const SubmissionId = IDL.Nat;
  
  return IDL.Service({
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFilteredProducts' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'submitForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [SubmissionId], []),
  });
};

export const init = ({ IDL }) => { return []; };